import turtle
def start(alexa):
  alexa.speed(0)
  alexa.penup() 
  alexa.goto(-200, -300)
  alexa.pendown()
  for i in range(4):
    alexa.forward(500)
    alexa.left(90)
  alexa.forward(15)
  for i in range(10):  
    for i in range(8):
      alexa.forward(20)
      alexa.left(45)
    alexa.forward(45)
  alexa.forward(30)
  alexa.penup()
  alexa.left(90)
  alexa.forward(45)
  alexa.pendown()
def secline(alexa):
  alexa.penup()
  alexa.left(90)
  alexa.forward(45)
  alexa.pendown()
def newline(alexa):
  alexa.penup()
  alexa.right(135)
  alexa.forward(15)
  alexa.right(180)
  alexa.forward(495)
  alexa.left(90)
  alexa.forward(45)
  alexa.pendown()
def SecLineAllOct(alexa):
  for i in range(9):
    for i in range(13):
      alexa.forward(20)
      alexa.left(45)
    alexa.right(45)
    alexa.left(180)
def LastOct(alexa):
  for i in range(13):
    alexa.forward(20)
    alexa.left(45)
alexa = turtle.Turtle()
wn = turtle.Screen()
start(alexa) # ref line 6
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
SecLineAllOct(alexa)
LastOct(alexa)
newline(alexa)
wn.exitonclick()